In [9]:
import pandas as pd
import glob
import sqlite3
#create variable to read in all csv files
files = "*.csv"
# create connection to db
con = sqlite3.connect('music_dashboard.db')
# create cursor object
cur = con.cursor()

albums_df = pd.concat(map(pd.read_csv, glob.iglob(files, recursive=True)))

albums_df

,artist,album,date,week_num,meta_score,user_score
0,Outkast,Stankonia,"October 31, 2000",44,95,88
1,Primal Scream,XTRMNTR,"May 2, 2000",18,90,88
2,Aimee Mann,"Bachelor No. 2 (or, the last remains of the dodo)","May 2, 2000",18,89,86
3,PJ Harvey,"Stories from the City, Stories from the Sea","October 24, 2000",43,88,88
4,The New Pornographers,Mass Romantic,"November 21, 2000",47,87,88
...,...,...,...,...,...,...
459,John Legend,Bigger Love,"June 19, 2020",25,59,71
460,Beach Slang,The Deadbeat Bang of Heartbreak City,"January 10, 2020",2,59,45
461,Katy Perry,Smile,"August 28, 2020",35,58,83
462,Justin Bieber,Changes,"February 14, 2020",7,57,51
463,Diplo,Chapter 1: Snake Oil,"May 29, 2020",22,46,33

In [10]:
albums_df.to_sql('albums', con, if_exists="replace")

In [18]:
cur.execute('select * from albums where "index" = "1"')
print(cur.fetchall())

[(1, 'Primal Scream', 'XTRMNTR', 'May 2, 2000', 18, 90, 88), (1, 'Los Super Seven', 'Canto', 'March 13, 2001', 11, 91, 76), (1, 'Tom Waits', 'Alice', 'May 7, 2002', 19, 90, 85), (1, 'Outkast', 'Speakerboxxx/The Love Below', 'September 23, 2003', 39, 91, 87), (1, 'Loretta Lynn', 'Van Lear Rose', 'April 27, 2004', 18, 97, 84), (1, 'My Morning Jacket', 'Z', 'October 4, 2005', 40, 90, 84), (1, 'Tom Waits', 'Orphans: Brawlers, Bawlers & Bastards', 'November 21, 2006', 47, 92, 88), (1, 'Burial', 'Untrue', 'November 6, 2007', 45, 90, 80), (1, 'Plush', 'Fed', 'August 25, 2008', 35, 89, 75), (1, 'Nirvana', 'Live At Reading', 'November 3, 2009', 45, 93, 88), (1, 'Janelle Monáe', 'The ArchAndroid', 'May 18, 2010', 20, 91, 89), (1, 'Saigon', 'The Greatest Story Never Told', 'February 15, 2011', 7, 89, 83), (1, 'The Menzingers', 'On the Impossible Past', 'February 21, 2012', 8, 93, 80), (1, 'Bassekou Kouyate & Ngoni Ba', 'Jama Ko', 'April 2, 2013', 14, 90, 63), (1, 'Behemoth', 'The Satanist', 'February 4, 2014', 6, 92, 85), (1, 'Sufjan Stevens', 'Carrie & Lowell', 'March 31, 2015', 14, 90, 89), (1, 'Beyoncé', 'Lemonade', 'April 23, 2016', 16, 92, 80), (1, 'Mount Eerie', 'A Crow Looked at Me', 'March 24, 2017', 12, 93, 80), (1, 'Rolo Tomassi', 'Time Will Die and Love Will Bury It', 'March 2, 2018', 9, 92, 72), (1, 'Weyes Blood', 'Titanic Rising', 'April 5, 2019', 14, 91, 90), (1, 'Bob Dylan', 'Rough and Rowdy Ways', 'June 19, 2020', 25, 95, 76)]

In [19]:
con.close()